package ledger

// Schema contains the PostgreSQL DDL for all ledger tables.
// No tenant_id, no api_keys, no tenants tables -- single-exchange challenge mode.
const Schema = `
-- Trade intents generated by strategy engines.
CREATE TABLE IF NOT EXISTS trade_intents (
    intent_id       TEXT PRIMARY KEY,
    strategy        TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    ts_ms           BIGINT NOT NULL,
    expires_ms      BIGINT NOT NULL,
    legs            JSONB NOT NULL DEFAULT '[]',
    expected        JSONB NOT NULL DEFAULT '{}',
    status          TEXT NOT NULL DEFAULT 'pending',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_intents_strategy ON trade_intents (strategy);
CREATE INDEX IF NOT EXISTS idx_intents_symbol ON trade_intents (symbol);
CREATE INDEX IF NOT EXISTS idx_intents_status ON trade_intents (status);
CREATE INDEX IF NOT EXISTS idx_intents_ts ON trade_intents (ts_ms);

-- Execution events tracking each step of order execution.
CREATE TABLE IF NOT EXISTS execution_events (
    id                      BIGSERIAL PRIMARY KEY,
    event_type              TEXT NOT NULL,
    intent_id               TEXT NOT NULL,
    leg_index               INT NOT NULL DEFAULT 0,
    symbol                  TEXT NOT NULL,
    action                  TEXT NOT NULL DEFAULT '',
    strategy                TEXT NOT NULL DEFAULT '',
    market                  TEXT NOT NULL DEFAULT '',
    requested_notional_usd  DOUBLE PRECISION NOT NULL DEFAULT 0,
    filled_notional_usd     DOUBLE PRECISION NOT NULL DEFAULT 0,
    filled_price            DOUBLE PRECISION NOT NULL DEFAULT 0,
    slippage_bps_actual     DOUBLE PRECISION NOT NULL DEFAULT 0,
    fees_usd_actual         DOUBLE PRECISION NOT NULL DEFAULT 0,
    ts_ms                   BIGINT NOT NULL,
    latency_ms              BIGINT NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_exec_events_intent ON execution_events (intent_id);
CREATE INDEX IF NOT EXISTS idx_exec_events_type ON execution_events (event_type);
CREATE INDEX IF NOT EXISTS idx_exec_events_ts ON execution_events (ts_ms);

-- Completed fill summaries (one per two-leg trade).
CREATE TABLE IF NOT EXISTS fills (
    id          BIGSERIAL PRIMARY KEY,
    intent_id   TEXT NOT NULL,
    strategy    TEXT NOT NULL,
    symbol      TEXT NOT NULL,
    buy_price   DOUBLE PRECISION NOT NULL,
    sell_price  DOUBLE PRECISION NOT NULL,
    total_fees  DOUBLE PRECISION NOT NULL,
    net_pnl     DOUBLE PRECISION NOT NULL,
    ts_ms       BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_fills_intent ON fills (intent_id);
CREATE INDEX IF NOT EXISTS idx_fills_strategy ON fills (strategy);
CREATE INDEX IF NOT EXISTS idx_fills_ts ON fills (ts_ms);
CREATE INDEX IF NOT EXISTS idx_fills_symbol ON fills (symbol);

-- Risk engine state snapshots.
CREATE TABLE IF NOT EXISTS risk_snapshots (
    id                  BIGSERIAL PRIMARY KEY,
    mode                TEXT NOT NULL,
    ts_ms               BIGINT NOT NULL,
    drawdown_pct        DOUBLE PRECISION NOT NULL DEFAULT 0,
    daily_drawdown_pct  DOUBLE PRECISION NOT NULL DEFAULT 0,
    peak_equity_usd     DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_equity_usd  DOUBLE PRECISION NOT NULL DEFAULT 0,
    error_rate_5m_pct   DOUBLE PRECISION NOT NULL DEFAULT 0,
    reason              TEXT NOT NULL DEFAULT '',
    challenge_phase     TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_risk_snap_ts ON risk_snapshots (ts_ms);
CREATE INDEX IF NOT EXISTS idx_risk_snap_mode ON risk_snapshots (mode);

-- Challenge progress tracking (one row per day).
CREATE TABLE IF NOT EXISTS challenge_progress (
    day                 TEXT PRIMARY KEY,
    equity              DOUBLE PRECISION NOT NULL,
    drawdown_pct        DOUBLE PRECISION NOT NULL DEFAULT 0,
    trades              INT NOT NULL DEFAULT 0,
    funding_collected   DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_challenge_day ON challenge_progress (day);

-- Funding payments received or paid on perpetual positions.
CREATE TABLE IF NOT EXISTS funding_payments (
    id          BIGSERIAL PRIMARY KEY,
    symbol      TEXT NOT NULL,
    rate        DOUBLE PRECISION NOT NULL,
    amount_usd  DOUBLE PRECISION NOT NULL,
    ts_ms       BIGINT NOT NULL,
    direction   TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_funding_pay_symbol ON funding_payments (symbol);
CREATE INDEX IF NOT EXISTS idx_funding_pay_ts ON funding_payments (ts_ms);
CREATE INDEX IF NOT EXISTS idx_funding_pay_dir ON funding_payments (direction);
`
